# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 300)
        LoginForm.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #000000;\n"
"        color: #00FF00;\n"
"        font-family: \"Consolas\";\n"
"    }\n"
"    QLineEdit {\n"
"        background-color: #001100;\n"
"        border: 1px solid #00FF00;\n"
"        padding: 6px;\n"
"        color: #00FF00;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #003300;\n"
"        color: #00FF00;\n"
"        border: 1px solid #00FF00;\n"
"        border-radius: 6px;\n"
"        padding: 6px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #004400;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitulo = QtWidgets.QLabel(LoginForm)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setStyleSheet("font-size: 22px; font-weight: bold; color: #00FF00;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.verticalLayout.addWidget(self.lblTitulo)
        self.txtUsuario = QtWidgets.QLineEdit(LoginForm)
        self.txtUsuario.setObjectName("txtUsuario")
        self.verticalLayout.addWidget(self.txtUsuario)
        self.txtPassword = QtWidgets.QLineEdit(LoginForm)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout.addWidget(self.txtPassword)
        self.btnLogin = QtWidgets.QPushButton(LoginForm)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout.addWidget(self.btnLogin)
        self.lblMensaje = QtWidgets.QLabel(LoginForm)
        self.lblMensaje.setText("")
        self.lblMensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMensaje.setStyleSheet("color: red;")
        self.lblMensaje.setObjectName("lblMensaje")
        self.verticalLayout.addWidget(self.lblMensaje)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Inicio de Sesión"))
        self.lblTitulo.setText(_translate("LoginForm", " MEDIDOR CARDÍACO"))
        self.txtUsuario.setPlaceholderText(_translate("LoginForm", "Usuario"))
        self.txtPassword.setPlaceholderText(_translate("LoginForm", "Contraseña"))
        self.btnLogin.setText(_translate("LoginForm", "Ingresar"))
