# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monitor.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        Form.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #000000;\n"
"        color: #00FF00;\n"
"        font-family: \"Consolas\";\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #003300;\n"
"        color: #00FF00;\n"
"        border: 1px solid #00FF00;\n"
"        border-radius: 6px;\n"
"        padding: 6px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #004400;\n"
"    }\n"
"    QComboBox {\n"
"        background-color: #001100;\n"
"        border: 1px solid #00FF00;\n"
"        padding: 4px;\n"
"        color: #00FF00;\n"
"    }\n"
"    QLabel {\n"
"        color: #00FF00;\n"
"    }\n"
"   ")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTitulo = QtWidgets.QLabel(Form)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitulo.setStyleSheet("font-size: 26px; font-weight: bold; color: #00FF00;")
        self.lblTitulo.setObjectName("lblTitulo")
        self.gridLayout.addWidget(self.lblTitulo, 0, 0, 1, 2)
        self.grafico = QtWidgets.QFrame(Form)
        self.grafico.setFrameShape(QtWidgets.QFrame.Box)
        self.grafico.setStyleSheet("background-color: black; border: 1px solid #00FF00;")
        self.grafico.setObjectName("grafico")
        self.layoutGrafico = QtWidgets.QVBoxLayout(self.grafico)
        self.layoutGrafico.setObjectName("layoutGrafico")
        self.gridLayout.addWidget(self.grafico, 1, 0, 1, 2)
        self.panelControles = QtWidgets.QVBoxLayout()
        self.panelControles.setObjectName("panelControles")
        self.lblPuerto = QtWidgets.QLabel(Form)
        self.lblPuerto.setObjectName("lblPuerto")
        self.panelControles.addWidget(self.lblPuerto)
        self.comboPuerto = QtWidgets.QComboBox(Form)
        self.comboPuerto.setObjectName("comboPuerto")
        self.panelControles.addWidget(self.comboPuerto)
        self.btnRefrescar = QtWidgets.QPushButton(Form)
        self.btnRefrescar.setObjectName("btnRefrescar")
        self.panelControles.addWidget(self.btnRefrescar)
        self.btnConectar = QtWidgets.QPushButton(Form)
        self.btnConectar.setObjectName("btnConectar")
        self.panelControles.addWidget(self.btnConectar)
        self.lblEstado = QtWidgets.QLabel(Form)
        self.lblEstado.setObjectName("lblEstado")
        self.panelControles.addWidget(self.lblEstado)
        self.gridLayout.addLayout(self.panelControles, 2, 0, 1, 1)
        self.panelDatos = QtWidgets.QVBoxLayout()
        self.panelDatos.setObjectName("panelDatos")
        self.lblBPMTexto = QtWidgets.QLabel(Form)
        self.lblBPMTexto.setStyleSheet("font-size: 18px; color: #00FF00;")
        self.lblBPMTexto.setObjectName("lblBPMTexto")
        self.panelDatos.addWidget(self.lblBPMTexto)
        self.lblBPM = QtWidgets.QLabel(Form)
        self.lblBPM.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBPM.setStyleSheet("font-size: 36px; font-weight: bold; color: #00FF00;")
        self.lblBPM.setObjectName("lblBPM")
        self.panelDatos.addWidget(self.lblBPM)
        self.lblClasificacion = QtWidgets.QLabel(Form)
        self.lblClasificacion.setAlignment(QtCore.Qt.AlignCenter)
        self.lblClasificacion.setStyleSheet("font-size: 20px; color: #00FF00;")
        self.lblClasificacion.setObjectName("lblClasificacion")
        self.panelDatos.addWidget(self.lblClasificacion)
        self.gridLayout.addLayout(self.panelDatos, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Monitor Cardíaco"))
        self.lblTitulo.setText(_translate("Form", "🩺 MONITOR CARDÍACO"))
        self.lblPuerto.setText(_translate("Form", "Puerto Serial:"))
        self.btnRefrescar.setText(_translate("Form", " Refrescar Puertos"))
        self.btnConectar.setText(_translate("Form", " Conectar"))
        self.lblEstado.setText(_translate("Form", "Desconectado"))
        
        # ----- TEXTOS MODIFICADOS -----
        self.lblBPMTexto.setText(_translate("Form", "Señal Análoga (0-1023):"))
        self.lblBPM.setText(_translate("Form", "--"))
        self.lblClasificacion.setText(_translate("Form", "En reposo..."))